version: '3'
services:
  minetest:
    container_name: minetest
    build: .
    ports:
      - "15326:30000/udp"
      - "15326:30000/tcp"
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    networks:
      - overlay_net
  udp_proxy:
    container_name: udp_proxy
    image: udp_proxy
    ports:
      - "30000/tcp"
      - "30000/udp"
      - "30000:20000/tcp"
      - "30000:20000/udp"
    depends_on:
      - minetest
    networks:
      - overlay_net
    volumes:
      - /tmp/udp_proxy.log:/tmp/udp_proxy.log
  client:
    container_name: client
    build: .
    depends_on:
      - udp_proxy
    ports:
      - "30000/udp"
      - "30000/tcp"
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - overlay_net
networks:
  overlay_net:
